[build]
  command = "curl -O https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.19.2-stable.tar.xz && tar xf flutter_linux_3.19.2-stable.tar.xz && export PATH=\"$PATH:$PWD/flutter/bin\" && flutter precache && flutter config --enable-web && flutter build web --release"
  publish = "build/web"

[build.environment]
  FLUTTER_VERSION = "stable"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200